export const FETCH_DETAIL_REQUEST = 'FETCH_DETAIL_REQUEST'; 
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS'; 
export const FETCH_DETAIL_FAIL = 'FETCH_DETAIL_FAIL';
export const GET_GUEST = 'GET_GUEST'
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION'
export const GET_CURRENT_DATE = 'GET_CURRENT_DATE'
export const FETCH_MORE_DETAIL = 'FETCH_MORE_DETAIL'; 
