export const FETCH_ROOM_REQUEST = 'FETCH_ROOM_REQUEST'; 
export const FETCH_ROOM_SUCCESS = 'FETCH_ROOM_SUCCESS'; 
export const FETCH_ROOM_FAIL = 'FETCH_ROOM_FAIL';
export const FETCH_COMMENT_REQUEST = 'FETCH_COMMENT_REQUEST'; 
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS'; 
export const FETCH_COMMENT_FAIL = 'FETCH_COMMENT_FAIL';