export const FETCH_INFORMATION_REQUEST = 'FETCH_INFORMATION_REQUEST'; 
export const FETCH_INFORMATION_SUCCESS = 'FETCH_INFORMATION_SUCCESS'; 
export const FETCH_INFORMATION_FAIL = 'FETCH_INFORMATION_FAIL';
export const FETCH_TICKETS_REQUEST = 'FETCH_TICKETS_REQUEST'; 
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'; 
export const FETCH_TICKETS_FAIL = 'FETCH_TICKETS_FAIL';